//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CreateRssUrlDefault {
            get {
                return ResourceManager.GetString("CreateRssUrlDefault", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string ContactsTelegramLink {
            get {
                return ResourceManager.GetString("ContactsTelegramLink", resourceCulture);
            }
        }
        
        public static string ContactsMailLink {
            get {
                return ResourceManager.GetString("ContactsMailLink", resourceCulture);
            }
        }
        
        public static string ContactsLinkedInLink {
            get {
                return ResourceManager.GetString("ContactsLinkedInLink", resourceCulture);
            }
        }
        
        public static string ContactsDiscordLink {
            get {
                return ResourceManager.GetString("ContactsDiscordLink", resourceCulture);
            }
        }
        
        public static string RssDeleteDialogTitle {
            get {
                return ResourceManager.GetString("RssDeleteDialogTitle", resourceCulture);
            }
        }
        
        public static string FilterFromTitle {
            get {
                return ResourceManager.GetString("FilterFromTitle", resourceCulture);
            }
        }
        
        public static string FilterToTitle {
            get {
                return ResourceManager.GetString("FilterToTitle", resourceCulture);
            }
        }
        
        public static string RssFeedItemUpdated {
            get {
                return ResourceManager.GetString("RssFeedItemUpdated", resourceCulture);
            }
        }
        
        public static string RssFeedItemNotUpdated {
            get {
                return ResourceManager.GetString("RssFeedItemNotUpdated", resourceCulture);
            }
        }
        
        public static string AnimationWeaverTitle {
            get {
                return ResourceManager.GetString("AnimationWeaverTitle", resourceCulture);
            }
        }
        
        public static string AnimatableFragmentGoNext {
            get {
                return ResourceManager.GetString("AnimatableFragmentGoNext", resourceCulture);
            }
        }
        
        public static string AnimatableFragmentGoBack {
            get {
                return ResourceManager.GetString("AnimatableFragmentGoBack", resourceCulture);
            }
        }
        
        public static string AnimationTypeNone {
            get {
                return ResourceManager.GetString("AnimationTypeNone", resourceCulture);
            }
        }
        
        public static string AnimationTypeLeft {
            get {
                return ResourceManager.GetString("AnimationTypeLeft", resourceCulture);
            }
        }
        
        public static string AnimationTypeRight {
            get {
                return ResourceManager.GetString("AnimationTypeRight", resourceCulture);
            }
        }
        
        public static string AnimationTypeTop {
            get {
                return ResourceManager.GetString("AnimationTypeTop", resourceCulture);
            }
        }
        
        public static string AnimationTypeBottom {
            get {
                return ResourceManager.GetString("AnimationTypeBottom", resourceCulture);
            }
        }
        
        public static string AnimationTypeExplode {
            get {
                return ResourceManager.GetString("AnimationTypeExplode", resourceCulture);
            }
        }
        
        public static string AnimationTypeFade {
            get {
                return ResourceManager.GetString("AnimationTypeFade", resourceCulture);
            }
        }
    }
}
